# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/lib/pq"
  revision = "90697d60dd844d5ef6ff15135d0203f65d2f53b8"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  revision = "0dae4fefe7c0e190f7b5a78dac28a1c82cc8d849"

[[constraint]]
  branch = "master"
  name = "github.com/ethereum/go-ethereum"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "github.com/joincivil/go-common"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"
